PenguinV/unit_tests/unit_test_helper.h

This fixes the tests not compiling on OSX, and closes issue #14.

Added cstdlib include for the function 'rand'

---

PenguinV/unit_tests/Makefile

As I don't have Visual Studio installed, I think it'd be great if we support building with `make`.

Add Makefile for unittest

---

API_description.md
PenguinV/Library/image_function_neon.cpp
PenguinV/Library/image_function_neon.h
PenguinV/unit_tests/unit_test_image_function_neon.cpp
PenguinV/unit_tests/unit_test_image_function_neon.h

Maximum, Minimum and Subtract Operations

Added image function and unit tests for Neon Instruction

---

src/fft.cpp
src/fft.h

Fix FFT compilation

---

examples/bitmap_operation/README.md
examples/blob_detection/README.md
examples/function_pool/README.md
examples/image_function/README.md
examples/median_filter/README.md
examples/thread_pool/README.md

Fixes #128 
Included missing files in the g++ compilation line.

Fixed g++ compilation

---

src/penguinv/cpu_id_unix.h

fix the cpuid problem with arm processor

---

examples/makefile

Added a makefile which uses recursive make to build example programs using their own makefiles.
The makefile does not stop on failed compilations.
Fixes #129

Added makefile to build examples

---

src/penguinv/cpu_identification.h

Merged apple and linux macros

---

src/image_function_simd.cpp
src/image_function_simd.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #113. I add the avx support for the accumulate function, the only thing I found weird in my implementation is it seems to be slower on larger dataset:
I should implement the sse support in the following days.

add avx support for the accumulate function

---

src/image_function_simd.cpp
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

the performance for the sse support:

add sse support for the accumulate function

---

src/math_base.h

Fix segfault for blob detection code execution on Linux

---

src/image_function.cpp

Fix for issue reported in https://github.com/ihhub/penguinV/issues/187

Use sigle buffer allocation/deallocation

---

.travis.yml
appveyor.yml
test/CMakeLists.txt
test/unit_tests/CMakeLists.txt
test/unit_tests/opencl/CMakeLists.txt
test/unit_tests/opencl/unit_tests_opencl.cpp

Adding CMake config for test/unit_tests/opencl

Add OpenCL check in CMake and add cmake files for unit tests

---

examples/blob_detection/README.md
examples/blob_detection/example_blob_detection.vcxproj
examples/blob_detection/makefile
src/blob_detection.cpp
src/blob_detection.h
src/math/hough_transform.cpp
src/math/hough_transform.h
src/math/math_base.cpp
src/math/math_base.h
test/performance_tests/CMakeLists.txt
test/performance_tests/Makefile
test/performance_tests/README.md
test/performance_tests/performance_tests.vcxproj
test/unit_tests/CMakeLists.txt
test/unit_tests/Makefile
test/unit_tests/README.md
test/unit_tests/unit_test_helper.cpp
test/unit_tests/unit_test_helper.h
test/unit_tests/unit_test_math.cpp
test/unit_tests/unit_test_math.h
test/unit_tests/unit_tests.cpp
test/unit_tests/unit_tests.vcxproj

Add Hough transform

---

script/travis/run_script.sh

Run cppclean on src, test, examples only.

---

src/cuda/image_function_cuda.cu
src/image_function.cpp
src/image_function_simd.cpp
src/opencl/image_function_opencl.cpp

I hope that this is what you meant. Resolves #217

Removed FunctionRegistrator inheritance from penguinV::FunctionTable

---

src/thirdparty/kissfft/kiss_fft.c
test/unit_tests/CMakeLists.txt
test/unit_tests/unit_test_fft.cpp
test/unit_tests/unit_test_fft.h
test/unit_tests/unit_test_helper.cpp
test/unit_tests/unit_test_helper.h
test/unit_tests/unit_tests.cpp
test/unit_tests/unit_tests.vcxproj

Added unit tests for FFT CPU based classes.

Add unit tests for FFT

---

examples/bitmap_operation/README.md
examples/bitmap_operation/example_bitmap_operation.vcxproj
examples/bitmap_operation/makefile
examples/blob_detection/README.md
examples/blob_detection/example_blob_detection.vcxproj
examples/blob_detection/makefile
examples/cuda/image_function/example_image_function.vcxproj
examples/image_function/README.md
examples/image_function/example_image_function.vcxproj
examples/image_function/makefile
examples/median_filter/example_median_filter.vcxproj
examples/opencl/image_function/image_function.vcxproj
examples/opencl/image_function/makefile
examples/qt_framework/qimage_display/CMakeLists.txt
src/cuda/image_function_cuda.cu
src/image_function.cpp
src/image_function_helper.cpp
src/image_function_helper.h
src/image_function_simd.cpp
src/opencl/image_function_opencl.cpp
src/penguinv/penguinv.cpp
src/penguinv/penguinv.h
test/performance_tests/cuda/performance_tests_cuda.vcxproj
test/unit_tests/CMakeLists.txt
test/unit_tests/cuda/Makefile
test/unit_tests/cuda/unit_tests_cuda.vcxproj
test/unit_tests/opencl/CMakeLists.txt
test/unit_tests/opencl/Makefile
test/unit_tests/opencl/unit_tests_opencl.vcxproj

Remove `penguinv.cpp` dependencies from almost all files.

Image function restructure

---

test/unit_tests/unit_test_image_function.cpp

Include BinaryDilate and BinaryErode functions in unit tests

---

src/python/README.md

Add notes on Windows to python README.md

---

src/image_function_simd.cpp
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/Makefile
test/unit_tests/unit_test_image_function.cpp

PR for #116.
performance when horizontal is false:
performance when horizontal is true:

Projection profile for SSE4.2

---

src/edge_detection.cpp
src/edge_detection.h
test/unit_tests/CMakeLists.txt
test/unit_tests/Makefile
test/unit_tests/unit_test_edge_detection.cpp
test/unit_tests/unit_test_edge_detection.h
test/unit_tests/unit_tests.cpp
test/unit_tests/unit_tests.vcxproj

Add gradient based edge detection

---

examples/bitmap_operation/example_bitmap_operation.cpp
examples/blob_detection/example_blob_detection.cpp
examples/cuda/image_function/example_image_function.cpp
examples/cuda/pinned_memory/pinned_memory.cpp
examples/filters/example_filters.cpp
examples/function_pool/example_function_pool.cpp
examples/image_function/example_image_function.cpp
examples/opencl/image_function/main.cpp
examples/qt_framework/qimage_display/main.cpp
examples/raspicam/main.cpp
examples/thread_pool/example_thread_pool.cpp

Changed error codes for examples

---

examples/qt_framework/qimage_display/CMakeLists.txt
examples/qt_framework/qimage_display/example_qimage_display.pro
examples/qt_framework/qimage_display/main.cpp
src/ui/qt/qt_ui.cpp
src/ui/qt/qt_ui.h
src/ui/qt/qt_ui.pri
src/ui/ui.cpp
src/ui/ui.h

Add base classes for image display with QT support

---

src/image_function_simd.cpp
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #116 
here's the performance on my raspberry pi when horizontal is false:
when horizontal is true:

Projection profile neon

---

src/image_function.cpp
src/image_function.h
src/image_function_helper.cpp
src/image_function_helper.h
test/unit_tests/unit_test_image_function.cpp

Add Shift function

---

src/file/bmp_image.cpp
test/unit_tests/unit_test_bitmap.cpp

Proper support of 256 color bitmaps

---

src/tool/light_correction.cpp
src/tool/light_correction.h

Add light correction class

---

src/image_function_helper.cpp
src/image_function_helper.h
src/image_function_simd.cpp
src/image_function_simd.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

Relates to #207  as needed step before real implementation.

Move simd control code into helper files

---

src/image_function_helper.cpp
src/image_function_helper.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

Removed function definitions from tests.
Related to #264

Remove duplicated function definitions

---

src/math/math_base.h

Add function to find line based on points

---

test/unit_tests/unit_test_helper.cpp
test/unit_tests/unit_test_helper.h
test/unit_tests/unit_test_image_function.cpp

Add unit tests for RgbToBgr function

---

src/image_function_simd.cpp
src/image_function_simd.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

the SSE version is ready to test, only the unit_test for RgbToBgr is missing
relates to #117

SSE implementation of RgbToBgr() function

---

src/image_function_simd.cpp
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #117 
here's the performance test:

NEON implementation of RgbToBgr() function

---

src/image_function.cpp
src/image_function.h
src/image_function_helper.cpp
src/image_function_helper.h
test/unit_tests/unit_test_image_function.cpp

Histogram calculation with mask

---

src/image_function_simd.cpp
src/image_function_simd.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #115 
Here's the performance:

SSE implementation of ConvertToRgb function

---

src/image_function_simd.cpp
test/performance_tests/Makefile
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/Makefile
test/unit_tests/unit_test_image_function.cpp

PR for #350 and #115.
all unit test pass:
Here's the performance test:

neon implementation of ConvertToRgb function

---

.travis.yml

Build Python Module on TravisCI

---

.travis.yml

Python 3.7 is not available on Ubuntu 14.04 (Trusty). Using Python 3.6.

Travis builds Python Module with Python3

---

appveyor.yml

Build Python Module on Appveyor with Python 2.7

---

src/penguinv/cpu_identification.h

Add MinGW compiler support

---

appveyor.yml
test/performance_tests/CMakeLists.txt
test/performance_tests/opencl/CMakeLists.txt
test/performance_tests/opencl/Makefile
test/performance_tests/opencl/performance_test_helper_opencl.cpp
test/performance_tests/opencl/performance_test_helper_opencl.h
test/performance_tests/opencl/performance_test_image_function_opencl.cpp
test/performance_tests/opencl/performance_test_image_function_opencl.h
test/performance_tests/opencl/performance_tests_opencl.cpp
test/performance_tests/opencl/performance_tests_opencl.vcxproj

Add OpenCL performance tests

---

src/opencl/image_function_opencl.cpp
src/opencl/image_function_opencl.h
src/opencl/opencl_device.cpp
src/opencl/opencl_device.h

relates to #368 
relates to #244

Add OpenCL Normalize function and CPU support

---

src/image_function_simd.cpp
src/image_function_simd.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #357 
performance when horizontal = true, vertical = false:
performance when horizontal = true, vertical = true:

SSE implementation of Flip function

---

src/image_function_simd.cpp

PR for #87 
the function work with any function except the projection profile function

Processing acceleration of full row ROI

---

.clang-format
src/opencl/image_function_opencl.cpp
src/opencl/opencl_types.h
test/unit_tests/opencl/unit_test_helper_opencl.cpp

Add base OpenCL types support

---

src/image_function.cpp
src/image_function_simd.cpp
src/parameter_validation.h

Processing acceleration for full width ROI

---

README.md

Added several links to various directories/files mentioned in README.md.
Can modify the page further.
Better user experience when navigating through the repo.
N/A
Fixes #321

Add a few links to README for better user experience

---

examples/function_pool/example_function_pool.cpp
examples/thread_pool/example_thread_pool.cpp
src/edge_detection.cpp
src/file/png_image.cpp
src/image_function.cpp
src/image_function_simd.cpp
src/opencl/opencl_device.cpp
test/unit_tests/unit_test_image_buffer.cpp
test/unit_tests/unit_test_image_function.cpp

Compilation warnings are potential errors in code. Fixing them would provide us a cleaner compilation where we can catch a real problem.

Fix compilation warnings

---

.travis.yml

[Issue #356] Moved specific script parts to related environments

---

src/image_function_simd.cpp
src/penguinv/cpu_identification.h

Fix SSSE3 compilation if no such macro exists

---

src/tool/ui/tool_ui.h
src/ui/win/win_ui.cpp

Histogram and projection profile visualizer class based on existing UI Window

---

test/unit_tests/unit_test_helper.cpp

Speed up unit tests

---

src/image_buffer.h
src/image_function.cpp
src/image_function.h

Add ConvertTo16Bit() and ConvertTo8Bit() functions

---

src/image_function.cpp
src/image_function.h
src/image_function_helper.h
test/unit_tests/unit_test_image_function.cpp

Replace channel

---

src/parameter_validation.h

Parameter validation

---

examples/edge_detection/example_edge_detection.cpp
src/edge_detection.cpp
src/edge_detection.h
test/unit_tests/unit_test_edge_detection.cpp

Rename EdgeDetection and clear data before finding edge points

---

src/image_function.cpp
src/image_function.h
src/image_function_helper.cpp
src/image_function_helper.h

Add ROI support for Rotate function

---

src/math/math_base.cpp
src/math/math_base.h
test/unit_tests/unit_test_helper.cpp
test/unit_tests/unit_test_math.cpp
test/unit_tests/unit_tests.cpp

- small unit tests speed up
- add more unit tests for math code
- code cleanup

Restructuring unit tests

---

src/blob_detection.cpp
src/blob_detection.h

Removed the duplicate code from both member functions and creating a helper function too. Hoping this is exactly what you were looking for!
relates to #427

Remove duplication code in BlobInfo class

---

src/image_function_simd.cpp

add tmmintrin header file under PENGUINV_SSSE3_SET macro

---

examples/raspicam/main.cpp

Change imageException to std::exception in catch block in Raspicam example

---

src/cuda/filtering_cuda.cu
src/cuda/image_function_cuda.cu
src/filtering.cpp
src/opencl/image_function_opencl.cpp

Replace math.h includes with cmath

---

src/image_function_helper.cpp
src/image_function_helper.h
src/penguinv/penguinv.cpp
src/penguinv/penguinv.h

Complete penguinv namespace API

---

src/edge_detection.cpp
src/image_function.cpp
src/math/hough_transform.cpp

Fix some compilation warnings
relates to #462

Compilation warning fixes

---

src/function_pool.cpp
src/function_pool_task.cpp
src/function_pool_task.h

Add a support for multiple input/output images

---

doc/API_description.md
src/function_pool.cpp
src/function_pool.h
test/unit_tests/unit_test_image_function.cpp

Implement multithreaded version Split function

---

src/image_function_helper.cpp
src/image_function_helper.h
src/penguinv/image_manager.h
src/penguinv/penguinv.cpp

Move image manager from penguinV.cpp file into common place

---

src/image_buffer.h
src/image_function.cpp
src/image_function_helper.cpp
src/image_function_helper.h
test/test_helper.cpp
test/test_helper.h
test/unit_tests/unit_test_helper.cpp
test/unit_tests/unit_test_helper.h
test/unit_tests/unit_test_image_function.cpp

Add unit tests support for 16-bit images

---

.travis.yml
CMakeLists.txt
script/travis/install_qt5.sh

Issue 469: Merging CUDA and Qt Travis jobs

---

src/image_function_simd.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #431.
the unit_test work on my side:

Add ConvertTo16Bit() function by AVX

---

src/cuda/cuda_memory.cuh
src/image_buffer.h
src/memory/cpu_memory.h
src/memory/memory_allocator.h
src/opencl/opencl_memory.h
test/performance_tests/performance_tests.cpp
test/unit_tests/unit_tests.cpp

Memory allocator implementation for CPU

---

src/image_function_simd.cpp
src/image_function_simd.h
test/unit_tests/unit_test_image_function.cpp

PR for #431.
the test work on my side:

Add ConvertTo8Bit() SSE function implementation

---

src/image_function.cpp

Optimise Dilate() function performance

---

CMakeLists.txt

Disable warning for CUDA compilation

---

src/cuda/cuda_memory.cuh
src/memory/cpu_memory.h
src/memory/memory_allocator.h
src/opencl/opencl_memory.h

Fixed "chunck" spelling issue per Issue #489

Fixed chunck spelling issue

---

src/file/png_image.cpp
test/unit_tests/CMakeLists.txt
test/unit_tests/Makefile
test/unit_tests/README.md
test/unit_tests/unit_test_png.cpp
test/unit_tests/unit_test_png.h
test/unit_tests/unit_tests.cpp
test/unit_tests/unit_tests.vcxproj

Add unit tests for PNG file type

---

src/cuda/image_function_cuda.cu
src/cuda/image_function_cuda.cuh

Cuda implementation of IsEqual() function

---

examples/file_operation/makefile

@ihhub could you look, please?
This fix seems strange as for me, but works on my computer.

Fix makefile for "file_operation" example

---

src/cuda/cuda_device.cuh
src/cuda/cuda_memory.cuh
src/cuda/cuda_types.cuh
src/cuda/image_buffer_cuda.cuh
src/fft.cpp
src/filtering.cpp
src/memory/cpu_memory.h
src/opencl/opencl_memory.h
test/test_helper.h
test/unit_tests/cuda/unit_test_helper_cuda.cuh

- fix #501 
- fix #499 
- fix #504

Fix multiple optimisation issues

---

src/cuda/filtering_cuda.cu

Remove duplicated code for Gaussian kernel creation

---

src/opencl/image_function_opencl.cpp
src/opencl/opencl_device.cpp

Fix race condition in OpenCL code

---

src/blob_detection.cpp

Optimise blob detection code by using image class instead of std::vector

---

src/image_function_simd.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #431 
here's the unit_test for this function:

implement convertTo8bit for neon

---

src/image_function_simd.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #431 
I implemented the ConvertTo16Bit function for neon. All unit tests passed:

implement ConvertTo16Bit function for neon

---

.travis.yml
test/performance_tests/cuda/Makefile

Hello, @ihhub.
It was a bit difficult to find time to solve this issue sorry for this.
I've made this makefile but have no possibility to check it. So, Could you look?

Makefile for CUDA performance tests (WIP #144)

---

src/ui/x11/x11_ui.cpp

Add static cast to uint32_t in x11_ui.cpp

---

src/blob_detection.cpp
src/opencl/image_function_opencl.cpp
src/opencl/image_function_opencl.h

OpenCL implementation of ProjectionProfile() function

---

.travis.yml
examples/cuda/image_function/makefile
examples/cuda/pinned_memory/makefile
examples/makefile

Makefiles for CUDA examples

---

src/function_pool.cpp
src/function_pool.h
test/unit_tests/unit_test_image_function.cpp

Add muiltithreaded implementation of Merge function

---

src/image_function.cpp
src/image_function.h
src/image_function_helper.cpp
src/image_function_helper.h
src/parameter_validation.h
test/test_helper.cpp
test/test_helper.h
test/unit_tests/unit_test_image_function.cpp

Add RgbToRgba and RgbaToRgb

---

src/image_function_simd.cpp
test/unit_tests/unit_test_image_function.cpp

this function was the only one missing from #431 
here's the unit tests:

AVX implementation of ConvertTo8Bit() function

---

src/filtering.cpp
test/unit_tests/unit_test_framework.cpp
test/unit_tests/unit_test_image_function.cpp

Fix missing Prewitt (form 3) unit test

---

doc/API_description.md

Add missing information into API description

---

src/cuda/image_buffer_cuda.cuh
src/cuda/image_buffer_cuda_pinned.cuh
src/image_buffer.h
src/opencl/image_buffer_opencl.h
test/performance_tests/CMakeLists.txt
test/performance_tests/Makefile
test/performance_tests/performance_test_edge_detection.cpp
test/performance_tests/performance_test_edge_detection.h
test/performance_tests/performance_tests.cpp
test/performance_tests/performance_tests.vcxproj
test/test_helper.cpp
test/test_helper.h
test/unit_tests/unit_test_helper.cpp
test/unit_tests/unit_test_helper.h

relates to #263 
plus fix of all image classes

Add performance tests fo edge detection

---

doc/API_description.md

Add API description for shift function

---

src/cuda/image_function_cuda.cu
src/cuda/image_function_cuda.cuh
test/unit_tests/cuda/unit_test_helper_cuda.cu
test/unit_tests/cuda/unit_test_helper_cuda.cuh
test/unit_tests/cuda/unit_test_image_function_cuda.cpp
test/unit_tests/unit_test_image_function.cpp

Add all forms of Flip function for CUDA

---

test/unit_tests/opencl/unit_test_helper_opencl.cpp
test/unit_tests/opencl/unit_test_helper_opencl.h

- Add additional verifyImage functions to OpenCL test helper.
- Add offset computation in function.
Tasks: https://github.com/ihhub/penguinV/issues/544

Modify verifyImage function and add offset computation

---

src/cuda/image_function_cuda.cu
src/image_function.cpp
src/image_function_helper.cpp
src/image_function_helper.h
src/opencl/image_function_opencl.cpp

Move existing duplicated code from GammaCorrection() into on function

---

src/image_function.cpp

Followed the instructions in #548

Modify Histogram() function to support color images

---

.gitignore
src/cuda/image_function_cuda.cu
src/cuda/image_function_cuda.cuh
test/unit_tests/cuda/unit_test_image_function_cuda.cpp

As the title suggests, this PR solves #538 .  Unit tests included.

Cuda implementation of SetPixel() function

---

src/opencl/image_function_opencl.cpp

Added support for color images into OpenCL LookupTable() function (#547)

---

.gitignore

Some useful .gitignore additions as discussed here https://github.com/ihhub/penguinV/pull/556#discussion_r331737013

Useful .gitignore additions

---

src/image_function_helper.cpp
src/image_function_helper.h
src/image_function_simd.cpp
src/penguinv/cpu_id_unix.h
src/penguinv/cpu_id_windows.h
src/penguinv/cpu_identification.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #86 
this PR implement the basic support of AVX512 BW.

Support AVX512_BW

---

src/image_function_simd.cpp
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #563 
I added three new function for AVX512 support.
The performance_tests and unit_tests compile with march=skylake-avx512

Accumulate, BitwiseAnd and BitwiseOr implementation

---

.travis.yml
CMakeLists.txt
src/penguinv/cpu_id_unix.h
src/penguinv/cpu_identification.h

Add ARM64 support to Travis-CI

---

appveyor.yml

We will have scheduled daily jobs as it's done for Travis-CI

Set unit test count to 500 for scheduled jobs in Appveyor

---

src/cuda/image_function_cuda.cu
src/cuda/image_function_cuda.cuh

- Add CUDA implementation for ProjectionProfile
#371

Add CUDA ProjectionProfile Implementation

---

test/unit_tests/unit_test_image_function.cpp

Add unit tests for IsBinary() function

---

test/unit_tests/cuda/unit_test_image_function_cuda.cpp

- Added 4 unit tests for ProjectionProfile.
Reference: https://github.com/ihhub/penguinV/issues/579

[CUDA] ProjectionProfile unit test

---

src/file/raw_image.h
src/image_function.cpp

Nobody likes compilation warnings

Compilation warning fix

---

src/image_function_helper.cpp
src/image_function_simd.cpp
src/penguinv/cpu_id_unix.h
src/penguinv/cpu_id_windows.h
src/penguinv/cpu_identification.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

PR for #582 #86.
Since we are now not only detecting AVX512BW, this PR check if AVX512CD, AVX512DQ, AVX512F and AVX512VL is available by the CPU. Also, this PR rename AVX512BW for AVX512SKL.

AVX-512 code refactoring

---

src/math/math_base.cpp
src/math/math_base.h
test/unit_tests/unit_test_math.cpp

WIP #320 
Hi, @ihhub. Look, please. Do we need some unit tests for these methods?

Add projection() and opposite() methods to LineBase2D class

---

test/unit_tests/unit_test_image_function.cpp

It should fix Windows job failure for Travis-CI

Fix a corner case for IsBinary() function

---

.travis.yml

Remove performance tests from Travis-CI jobs

---

src/opencl/opencl_device.cpp
src/opencl/opencl_device.h
src/opencl/opencl_helper.cpp
src/opencl/opencl_helper.h
src/opencl/opencl_memory.h

and fixed memory allocation issue

Add full CPU support for OpenCL

---

src/image_function.cpp
src/image_function_simd.cpp

- fix ConvertToRgb() function
- fix compilation warnings

Multiple fixes for SIMD code

---

README.md
src/file/file_image.cpp
src/file/jpeg_image.cpp
src/image_buffer.h
test/unit_tests/CMakeLists.txt
test/unit_tests/Makefile
test/unit_tests/unit_test_file.cpp
test/unit_tests/unit_tests.vcxproj

README example correction and JPEG support preparations

---

src/file/jpeg_image.cpp
src/file/jpeg_image.h
test/unit_tests/unit_test_file.cpp

Add full support of JPEG files

---

.travis.yml

and make static analysis job be lower

Add human readable job names

---

examples/blob_detection/example_blob_detection.cpp
examples/qt_framework/qimage_display/main.cpp
examples/raspicam/main.cpp
src/blob_detection.cpp
src/blob_detection.h

Rename CRITERION to BY for BlobDetection enumeration

---

src/function_pool.cpp
src/function_pool.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

Flip() function implementation in function pool

---

src/function_pool.cpp
src/function_pool.h
src/function_pool_task.cpp
src/function_pool_task.h
test/performance_tests/performance_test_image_function.cpp
test/unit_tests/unit_test_image_function.cpp

Implementation of Transpose function in function pool

---

.travis.yml

Set multicore compilation from CMake

---

.travis.yml
examples/python/bitmap_operation.py

to optimise job execution time

Review package installation on Travis-CI

---

appveyor.yml

Visual Studio 2015 image is set at the very beginning of the script.

Remove VS duplication for Python

---

.travis.yml

Remove yasm from Travis package installation

---

appveyor.yml

Cache CUDA installation for AppVeyor

---

src/image_function_simd.cpp

Add missing code for SIMD functions

---

cmake/find_png.cmake

Cache zlib for Appveyor

---

cmake/find_jpeg.cmake

Cache JPEG for Appveyor

---

cmake/find_png.cmake

Cache PNG for AppVeyor

---

examples/python/bitmap_operation.py

small code recommendation fix as well

Code cleanup for Python example

---

src/image_function_simd.cpp

Remove extra condition for Threshold AVX function

---

.travis.yml

and it's preinstalled in virtual machine image

Remove QT installation for OSX

---

src/file/bmp_image.cpp
src/image_function.cpp

Small code optimisation

---

src/fft.cpp
src/fft.h

Add an extra constructor for easier usage of FFT class

---

examples/file_operation/CMakeLists.txt
src/fft.cpp
src/file/raw_image.h

[here](https://lgtm.com/projects/g/ihhub/penguinV/alerts/?mode=list) is the list of code quality issues

Fix some code quality issues

---

.travis.yml

Don't waste time for useless cloning

Clone only last 50 commits of cppclean

---

examples/file_operation/CMakeLists.txt

right now it causes Windows builds in Travis-CI to fail

Remove library search for the example

---

doc/API_description.md
examples/raspicam/main.cpp
src/blob_detection.cpp
src/cuda/filtering_cuda.cu
src/cuda/image_function_cuda.cu
src/edge_detection.cpp
src/file/bmp_image.cpp
src/file/jpeg_image.cpp
src/file/png_image.cpp
src/file/raw_image.h
src/filtering.cpp
src/function_pool.cpp
src/function_pool_task.cpp
src/image_function.cpp
src/image_function_helper.cpp
src/image_function_simd.cpp
src/opencl/image_function_opencl.cpp
src/parameter_validation.h
src/tool/light_correction.cpp
test/unit_tests/unit_test_helper.cpp

Make few code changes in src/parameter_validation.h

---

src/file/bmp_image.cpp

Add a support for non-flipped Bitmaps

---

src/ui/win/win_ui.cpp
src/ui/win/win_ui.h

Fix displaying of huge images using WinAPI

---

src/blob_detection.cpp
src/file/bmp_image.cpp
src/file/png_image.cpp
src/filtering.cpp
src/function_pool.cpp
src/function_pool_task.cpp
src/image_function.cpp
src/image_function_simd.cpp
test/unit_tests/unit_test_helper.cpp

Make some code style corrections in existing code

---

src/image_buffer.h

Prevent variable overflow for > 4GB images

---

test/performance_tests/CMakeLists.txt
test/performance_tests/Makefile
test/unit_tests/CMakeLists.txt
test/unit_tests/Makefile

make more stricter compilation

Treat warnings as errors

---

src/blob_detection.cpp
src/blob_detection.h

We don't want to drop performance

Do not copy a whole structure for blob detection

---

src/thread_pool.cpp
src/thread_pool.h

Merge constructors for thread pool

---

.github/workflows/github_action.yml
appveyor.yml

we need to release AppVeyor resources

Compile Python on GitHub Actions

---

.travis.yml
script/travis/display_log_files.sh

Closes #253 
This adds a script to display the content of all log files in a folder.

Add script to output content of log files within a folder

---

.github/workflows/github_action.yml
README.md

- include performance tests build
- add code style checks
- update README file

Update GitHub Actions

---

.github/workflows/github_action.yml
.github/workflows/pr_author_auto_assign.yml
examples/blob_detection/example_blob_detection.cpp
script/check_code_format.sh

Fix GitHub actions pipeline

---

examples/file_operation/makefile
test/unit_tests/Makefile

Information about installing libpng and libjpg is OS-dependent

---

examples/file_operation/makefile
test/unit_tests/Makefile

Fixed png and jpeg libraries detection for macos

---

CMakeLists.txt
examples/cuda/image_function/CMakeLists.txt
examples/cuda/pinned_memory/CMakeLists.txt

added cuda examples to cmake

---

src/edge_detection.cpp
src/edge_detection.h
src/image_buffer.h
src/image_function_simd.cpp
src/math/hough_transform.cpp
src/math/hough_transform.h
src/math/math_base.h
src/memory/memory_allocator.h
test/unit_tests/unit_test_edge_detection.cpp
test/unit_tests/unit_test_file.cpp

This is the first batch of changes to update the code in preparation for multi-type image code changes.

Modernize the code (part 1)

---

test/performance_tests/cuda/performance_tests_cuda.vcxproj
test/performance_tests/opencl/performance_tests_opencl.vcxproj
test/unit_tests/cuda/unit_tests_cuda.vcxproj
test/unit_tests/opencl/unit_tests_opencl.vcxproj

To keep up to date with the rest of the code.

Update unit tests to Visual Studio 2019

---

.gitignore
test/performance_tests/cuda/performance_tests_cuda-vs2019-cuda12.4.vcxproj
test/unit_tests/cuda/unit_tests_cuda-vs2019-cuda12.4.vcxproj

Also, make it clear what version of VS is being used.

Make CUDA code compilable

---

examples/blob_detection/example_blob_detection.cpp
src/blob_detection.cpp
src/blob_detection.h
src/edge_detection.cpp
src/function_pool.cpp
src/math/haar_transform.cpp
src/math/hough_transform.cpp
src/math/math_base.h
src/memory/cpu_memory.h

This is the second batch of changes to update the code in preparation for multi-type image code changes.

Modernize the code (part 2)
