ihhub/penguinV

- PenguinV/Library/blob_detection.cpp
- PenguinV/examples/bitmap_operation/README.md
- PenguinV/examples/bitmap_operation/makefile
- PenguinV/examples/blob_detection/README.md
- PenguinV/examples/blob_detection/makefile
- PenguinV/examples/function_pool/README.md
- PenguinV/examples/function_pool/makefile
- PenguinV/examples/image_function/README.md
- PenguinV/examples/image_function/makefile
- PenguinV/examples/thread_pool/README.md
- PenguinV/examples/thread_pool/makefile
@ihhub:
- I added makefiles for all the examples, except `qt_framework` (I couldn't get that to build)
- in order to get `blob_detection` to build, I had to include `cmath`. See 0ccc908 (it wouldn't build using the instructions in the readme)
- I've relied on `make` as much as possible. Everything is laid out the same and will be easy for you to maintain. It'll also be clear to someone that knows make. It's always `target : dependencies`.
- Each of the executables are named after the C++ file instead of `application`. That allows the makefile to be minimal since make understands that. If you want everything to be copied, it can be done.
- The way it's set up, it will respect the dependencies listed. It doesn't create a dependency tree by running the compiler on the files. This is easier …
> Makefiles for examples

- PenguinV/Library/function_pool.cpp
I noticed that function_pool::getSum() is using sum.empty()  before returning.
The return type of which is ignored and the comment next to it seem to imply that clear() was the original intention...?
> Using vector::empty() instead of vector::clear()

- src/image_function_simd.cpp
- test/performance_tests/performance_test_image_function.cpp
- test/unit_tests/unit_test_image_function.cpp
PR for #106 all test unit_pass and performances are good. Here some screenshot ( I disabled a lot of test to avoid useless waiting ):
so the normal performance was: 0.16 sec / 0.70 sec / 2.8 sec / 11.12 sec
now the neon performance is:     0.04 sec / 0.17 sec / 1.1 sec / 3.691 sec
> add sum to arm neon

- src/image_function_simd.cpp
- src/image_function_simd.h
> Move `cpu_identification` include to from `.h` to `.cpp` file.

- examples/python/bitmap_operation.py
- src/python/penguinV.i
- src/python/setup.py
- Use os.path.join to support cross-platform paths.
- Windows supports forward slash in include paths, so changed paths to be compatible with Linux.
> Some fixes for python example in Linux.

- examples/bitmap_operation/README.md
- examples/bitmap_operation/makefile
- examples/blob_detection/README.md
- examples/blob_detection/makefile
- examples/image_function/README.md
- examples/image_function/makefile
- examples/thread_pool/README.md
- examples/thread_pool/makefile
Some entries were missing in following examples: bitmap_operation, blob_detection, image_function, example_thread_pool so linker gone wild. This one fixes #209
> Fixed dependencies in makefiles in certain examples, issue #209

- .travis.yml
- appveyor.yml
- test/unit_tests/CMakeLists.txt
We use an environment variable to set an input command line parameter for compiled `unit_tests` application. We set iteration count on unit tests to _500_ for **AppVeyor**.
Relates to #241
> Simplify unit test cmake file with environment variable support

- src/image_function_simd.cpp
- test/performance_tests/performance_test_image_function.cpp
- test/unit_tests/unit_test_image_function.cpp
PR for #117 
I found a way to implement it in AVX, it's not more performant, but it should avoid SSE/AVX switching penalties:
> AVX implementation of RgbToBgr() function

- src/image_function_simd.cpp
PR for #358. here's the performance on SSE:
I'm gonna upload the result for NEON later when I'm gonna have access to my pi.
> Add missing function registration for ConvertToRgb SIMD function

- src/ui/qt/qt_ui.cpp
- src/ui/qt/qt_ui.h
- src/ui/ui.cpp
- src/ui/ui.h
**`drawEllipse` function** - implemented from `QPainter::drawEllipse( int x,int y,int w, int h)` which refers to a rectangle with starting point (x,y), width w, and height h)
**Parameters:**
`Point2D center` - starting point referring to center of ellipse.
`int xDiameter` - Diameter in x axis, 
`int yDiameter `- Diameter in y axis
`PaintColor color` - color of drawn ellipse
**`drawRectangle` function**
**Parameters:**
`Point2D start` - starting point referring to upper left point of rectangle.
`int width` - width from starting point to its right direction.
`int height` - height from starting point to its bottom direction.
`PaintColor color` - color of drawn rectangle
Related to Issue #282
> Add oval and rectangle drawing support for UI Window Qt class

- src/filtering.cpp
- src/image_function.cpp
- src/image_function.h
- src/image_function_helper.cpp
- src/image_function_helper.h
- test/unit_tests/unit_test_image_function.cpp
- add unit tests for **ExtractChannel**() function
- add unit tests for **Merge**() function
- add unit tests for **Split**() function
- simplify **filterKernel** structure
- add an extra form of **Rotate**() function
relates to #265 , #429, #366, #367, #373
> Add unit tests for few functions

- CMakeLists.txt
With CMake there is no proper way to differentiate between Linux flavors. Nevertheless, I think the flag is only relevant for ARM targets. Therefore the provided fix should help. @0x72D0 Would you mind to test?
> Issue-458: Set mfpu=neon-vfpv4 as CMake compile option

- .clang-format
- src/image_function.h
> Disable check for a comment at the end of namespace during static analysis

- src/fft.cpp
> Use memory allocator instead of default memory allocation for FFT

- .travis.yml
- test/unit_tests/cuda/Makefile
@ihhub, look please.
When I was fixing  issue #144 I found out that makefile of cuda unit tests contains some old paths.
Maybe it would be better to fix it too?
> Modify old third-party paths in makefile of CUDA unit tests

- test/unit_tests/unit_test_file.cpp
> Do not run png unit tests if PNG support is disabled

- test/unit_tests/cuda/unit_test_image_function_cuda.cpp
- Rename the format of Test Cases to `{FunctionNameFormYTest}`
Reference task: https://github.com/ihhub/penguinV/issues/540
> Rename test names to format FunctionNameFormYTest

- src/cuda/image_function_cuda.cu
Fixes issue ( #546 )
The variable width is changed according to color, but is not used anywhere else. Isn't this a concern?
The variable width could be passed by reference instead.
> Added support in LookupTable() for CUDA to support color images (#546)

- src/opencl/image_function_opencl.cpp
- src/opencl/image_function_opencl.h
Closes #451 
Added `IsEqual` to `src/opencl/image_function_opencl.h` and `src/opencl/image_function_opencl.cpp`.
Also, added OpenCL kernel `isEqualOpenCL` to `src/opencl/image_function_opencl.cpp`.
> OpenCL implementation of IsEqual() function

- .travis.yml
- appveyor.yml
- test/test_helper.cpp
- test/unit_tests/unit_tests.cpp
We face a huge problem with building times for our project which recently became a disaster. The plan is to reduce unit test run time for all builds but have a daily build with heavy load on unit tests.
> Build time reduction for all builds on servers

- .travis.yml
From now we run all unit tests with count of 100 while we have daily job which we want to run with count 1000
> Set unit test count to 1000 for cron job only

- src/image_function_simd.cpp
- test/performance_tests/performance_test_image_function.cpp
- test/unit_tests/unit_test_image_function.cpp
PR for #86 
I added yet again three new function for AVX512 support.
The performance_tests and unit_tests compile with march=skylake-avx512
> BitwiseXor, ConvertTo16Bit, ConvertTo8Bit implementation for AVX512

- src/image_function_simd.cpp
- test/performance_tests/performance_test_image_function.cpp
- test/unit_tests/unit_test_image_function.cpp
PR for #86
I added yet again three new function for AVX512 support.
The performance_tests and unit_tests compile with march=skylake-avx512.
I can't test if the unit and performance tests work because I don't have a AVX512 processor in my possession.
I also fixes some missing code of my previous commit.
> Add Invert, Maximum, Minimum functions for AVX512

- src/penguinv/cpu_identification.h
here's a hotfix for #582.
It should solve the compilation problem only. We still need to add the flag identification for all the other avx512 module in cpu_id_unix.h and cpu_id_windows.h. Maybe also renaming PENGUINV_AVX512BW_SET define for PENGUINV_AVX512_SKYLAKE_SET since it's more accurate
> add more condition to enable avx512 compilation

- .travis.yml
Set Valgrind option "--show-reachable=no"
See http://valgrind.org/docs/manual/mc-manual.html
> Overwriting ctest MemoryCheckCommandOptions

- .travis.yml
Dynamic analysis job still fails so it's better to pass it until we find a concrete root of problem.
> Pass dynamic analysis always

- .travis.yml
- examples/file_operation/makefile
- test/unit_tests/Makefile
Travis-CI supports 2 cores per job so we should use it to improve our code compilation speed
> Speeding up ARM and Python compilation

- src/image_function_simd.cpp
- test/performance_tests/performance_test_image_function.cpp
- test/unit_tests/unit_test_image_function.cpp
PR for #86 
I've added the support for avx512 to ProjectionProfile, Sum and Substract. It compile with -march=skylake-avx512.
> AVX-512 implementation for ProjectionProfile, Sum and Subtract

- appveyor.yml
Like it's done in Travis-CI. It should slightly improve build time.
> Set default clone depth to 50 in AppVeyor

- src/file/bmp_image.cpp
Closes #644 
These changes optimize the [image saving function](https://github.com/ihhub/penguinV/blob/fa0b34e790ce8f0e149c8b4f1eb2a4819fc28226/src/file/bmp_image.cpp#L523) in **src/file/bmp_image.cpp**.
During the saving process, instead of copying a line of the pass image to a temporary array, along with the extra bytes needed for proper alignment, and then writing it into the output file; it writes the line from the image and the extra bytes for proper alignment directly into the file.
> Closes #644: Optimise Bitmap image saving function

- .github/workflows/github_action.yml
A default compiler for macOS is clang in comparison with gcc on Ubuntu.
> Add macOS compilation as a part of GitHub actions

- doc/opencl/API_description.md
- src/opencl/image_buffer_opencl.h
This is reasonably old version (2015) that should be supported by all modern systems.
close #699
> Set minimal OpenCL version to 2.1
